name: Terraform CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    terraform:
        name: 'Management_LZ_Core_Infra'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                    terraform_version: 1.0.0

              
            - name: Terraform Init
              run: terraform init -backend-config="path=mgt_rg.tfstate"
              working-directory: ./management_lz/infra

            - name: Terraform Validate
              run: terraform validate
              working-directory: ./management_lz/infra

            - name: Terraform Plan
              run: terraform plan -out=tfplan -state=mgt_rg.tfstate
              working-directory: ./management_lz/infra