name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Management_LZ_Core_Infra'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Azure CLI Login with Managed Identity
        run: az login --identity 

      - name: Terraform Init with Azure Backend
        run: terraform init -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" -backend-config="key=terraform.tfstate" -backend-config="access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
        working-directory: ./management_lz/infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./management_lz/infra

      - name: Terraform Plan
        run: terraform plan -out=tfplan  -var="statefile=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
        working-directory: ./management_lz/infra
