name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
 

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
      - name: Print Hello World
        run: echo "Hello, World!"